In [ ]:
#task1.1
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#task1.2
import numpy as np

array2D = np.random.randint(0, 10, size=(3, 3))
print(array2D)

[[2 2 9]
 [5 4 3]
 [4 7 5]]


In [12]:
#task2.1
array_sum = np.sum(array2D)
array_mean = np.mean(array2D)
array_max = np.max(array2D)

print("Sum:", array_sum)
print("Mean:", array_mean)
print("Max:", array_max)

Sum: 41
Mean: 4.555555555555555
Max: 9


In [13]:
#task2.2
arr_2x = array2D*2
print(arr_2x)

[[ 4  4 18]
 [10  8  6]
 [ 8 14 10]]


In [15]:
#task2.3
arr_replaced = array2D.copy()
arr_replaced[arr_replaced > 5] = 0
print(arr_replaced)

[[2 2 0]
 [5 4 3]
 [4 0 5]]
